name: Release AddOn

# triggers when pushing a tag
on:
  push:
    tags:
      - '**'

env:
  CF_API_KEY: ${{ secrets.CF_API_KEY }}
  WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
  GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }} # GitHub releases; automatically provided to the workflow

jobs:
  release: # you can name this anything you want
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: BigWigsMods/packager@master
